export const ADD_PATH = 'ADD_PATH';
export const GET_PATHS = 'GET_PATHS';
export const GET_PATHS_REQUESTED = 'GET_PATHS_REQUESTED';
export const ADD_PATH_REQUESTED = 'ADD_PATH_REQUESTED';

export const GET_PATH_DETAIL = 'GET_PATH_DETAIL';
export const GET_PATH_DETAIL_REQUESTED = 'GET_PATH_DETAIL_REQUESTED';
export const SET_PATH_DETAIL = 'SET_PATH_DETAIL';


export const UPDATE_PATH = 'UPDATE_PATH';
export const ADD_ITEM_REQUESTED = 'ADD_ITEM_REQUESTED';